---
- name: Basic Configuration for All Servers
  hosts: all
  become: yes
  roles:
   - common

- name: Configuring DB Servers
  hosts: appdbs
  become: yes
  roles:
   - db-tier

- name: Configuring Webservers
  hosts: apps
  become: yes
  roles:
   - app-tier

- name: configuring LB Servers
  hosts: frontends
  become: yes
  roles:
   - lb-tier