---
# tasks file for roles/lb-tier
- name: install Frontend Packages 
  yum:
    name: "{{ item }}" 
    state: latest
  with_items: 
    - httpie
    - haproxy

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Start HAproxy
  service:
    name: haproxy
    state: started
    enabled: yes
