---
# tasks file for roles/db-tier
- name: install postgres
  yum:
    name: postgresql-server
    state: present

- name: start postgres
  service:
    name: postgresql.service
    state: started
    enabled: yes
