---
# tasks file for roles/app-tier
- name: Install Tomcat
  yum:
    name: tomcat
    state: latest

- name: Create {{ TOMCAT_APP_DIR }} Tomcat Directory
  file:
    path: "{{ TOMCAT_APP_DIR }}"
    state: directory

- name: Copy static index.html to Tomcat {{ TOMCAT_APP_DIR }}/index.html
  template:
    src: index.html.j2
    dest: "{{ TOMCAT_APP_DIR }}/index.html"
    mode: 0644

- name: Start tomcat
  service:
    name: tomcat
    state: started
    enabled: yes

- name: install apache
  yum:
    name: httpd
    state: latest

- name: start apache
  service:
    name: httpd
    state: started
    enabled: yes
